// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcvruzjqnkojzyvpvfkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jdnJ1empxbmtvanp5dnB2ZmtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTk3NTEsImV4cCI6MjA2ODY3NTc1MX0.gi8wKGpKA5CES9CgsmHcnQkSsq4G_rXy406jvsgzJZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});